<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-NF15DBI" name="com.apparelStore.testCases.ApparelStoreTests" tests="12" failures="1" timestamp="09 Dec 2020 10:20:09 GMT" time="350.554" errors="0">
  <testcase name="itemsSearchTest" time="18.041" classname="com.apparelStore.testCases.ApparelStoreTests"/>
  <testcase name="placeOrder" time="73.294" classname="com.apparelStore.testCases.ApparelStoreTests"/>
  <testcase name="invalidLoginTest" time="22.969" classname="com.apparelStore.testCases.ApparelStoreTests"/>
  <testcase name="itemsSearchTest" time="18.318" classname="com.apparelStore.testCases.ApparelStoreTests"/>
  <testcase name="writeReviewTest" time="28.262" classname="com.apparelStore.testCases.ApparelStoreTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.apparelStore.testCases.ApparelStoreTests.writeReviewTest(ApparelStoreTests.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- writeReviewTest -->
  <testcase name="itemsSearchTest" time="19.067" classname="com.apparelStore.testCases.ApparelStoreTests"/>
  <testcase name="itemsSearchTest" time="18.405" classname="com.apparelStore.testCases.ApparelStoreTests"/>
  <testcase name="manufacturerTest" time="20.744" classname="com.apparelStore.testCases.ApparelStoreTests"/>
  <testcase name="validLoginTest" time="22.180" classname="com.apparelStore.testCases.ApparelStoreTests"/>
  <testcase name="logOffTest" time="34.992" classname="com.apparelStore.testCases.ApparelStoreTests"/>
  <testcase name="shareProductTest" time="35.252" classname="com.apparelStore.testCases.ApparelStoreTests"/>
  <testcase name="itemsSearchTest" time="39.030" classname="com.apparelStore.testCases.ApparelStoreTests"/>
</testsuite> <!-- com.apparelStore.testCases.ApparelStoreTests -->
